### PR TITLE
Add cross-compilation to build scripts, build libs in CI

### LINKED ISSUE #2: [Feature Request] Bundle compiled CPU-only libs into jar
Is it possible to use Github Actions to compile the llama.cpp libraries for CPU-only inference (to avoid needing multiple different variants per architecture and to avoid build dep issues in Actions) and include them in the built jar? [This project](https://github.com/GiviMAD/whisper-jni/tree/main) has a workflow that can be used to build off of. They use JNI instead of JNA, but the same methods should be usable. The resource folders containing the architecture-specific libraries need to be named a certain way though for JNA to find them: `{os-name}-{arch}`. The docs aren't super helpful on that, they imply on linux it should be `linux-amd64` but I could only get it to work by naming the resource folder `linux-x86-64`

I can help with this if you would like, but I can't test the workflow myself for obvious reasons

### PR DESCRIPTION
**Pull request by AutonomicPerfectionist**
This PR adds a job to the Github Actions workflow to build the libllama.so library for linux x86-64 and auto-include it in the maven artifact. It also adds cross-compilation support to the build scripts but does not yet add the built libs to the workflow until it can be verified to work correctly.

Fixes #2

### CODE REVIEW

**Comment by kherud** [comment]
Thank you for the PR! Do you happen to know how JNA searches for architecture specific libraries? I imagine that the particular sub-directory `linux-x86-64` nor its suffix don't make any difference, JNA just recursively looks for libraries in the resources. I am asking because I wonder if this causes any problems if we would add another library for the same platform but different architecture, for example `linux-arm64`. My optimistic estimate would be, that JNA just tries each library until it finds one it can use.

**Comment by AutonomicPerfectionist** [comment]
The documentation is a bit sparse on how JNA searches for the library, a bit of it is on the Getting Started page:

https://github.com/java-native-access/jna/blob/master/www/GettingStarted.md

The relevant section is this:
> Make your target library available to your Java program. There are several ways to do this:
>
> * The preferred method is to set the jna.library.path system property to the path to your target library. This property is similar to java.library.path, but only applies to libraries loaded by JNA.
> * Change the appropriate library access environment variable before launching the VM. This is PATH on Windows, LD_LIBRARY_PATH on Linux, and DYLD_LIBRARY_PATH on OSX.
> * Make your native library available on your classpath, under the path {OS}-{ARCH}/{LIBRARY}, where {OS}-{ARCH} is JNA's canonical prefix for native libraries (e.g. win32-x86, linux-amd64, or darwin). If the resource is within a jar file it will be automatically extracted when loaded.

We're using that third bullet point. Unfortunately, it seems the documentation there is outdated, as `linux-amd64` did not work for me; I had to use `linux-x86-64` for JNA to find the library. I tested on OpenJDK 11 on Pop OS 22.04, but it also works on Amazon Correto 11 in Flatpak (Intellij IDE).

**Comment by kherud** [comment]
Ok, I simplified the workflow a little bit and added linux-arm64 for testing, I hope that is ok:

- Directly checkout llama.cpp in the workflow
- Use github runners for the build environment instead of cmake toolchains. I'm no C++ expert but I think it's sufficient to keep things simple here. For different architectures we can use appropriate docker images with [qemu emulation](https://www.docker.com/blog/multi-arch-images/).
- Use the upload/download artifact name for the resources directory

I will test it in a second.

**Comment by kherud** [comment]
Ok, so the `linux-x86-64` build is now working and the library is published with the jar. Version 1.1.4 should soon be available for testing. The `linux-arm64` build isn't working yet, I'll figure that out tomorrow.

**Pull request merged**
