### PR TITLE
Set handling of special tokens in tokenizer to true

### LINKED ISSUE #45: Completion seems to ignore EOS token
I'm using your library with [phi-2](https://huggingface.co/TheBloke/dolphin-2_6-phi-2-GGUF) on an Android device (after updating the llama.cpp version). I've noticed that generation seems to ignore or skip end of stream tokens somehow. For example here's the output from `llama.cpp` itself:

prompt:
```
<|im_start|>system
You are a helpful assistant<|im_end|>
<|im_start|>user
hello<|im_end|>
<|im_start|>assistant
```

output:
```
<|im_start|>system
You are a helpful assistant
<|im_start|>user
hello
<|im_start|>assistant
Hello! How can I assist you today? [end of text]
```

When using jllama it looks like this:
```
<|im_start|>system
You are a helpful assistant
<|im_start|>user
hello
<|im_start|>assistant
Hello! How can I assist you today?<|im_end|>
<|im_start|>user
[more output]
```

Note that the text includes the token, and the start token for the next user prompt, which the model is self-generating ;)

Looking at the llama.cpp source, it seems to be stopping here https://github.com/ggerganov/llama.cpp/blob/master/examples/main/main.cpp#L896 and there's a similar condition in jjlama here: https://github.com/kherud/java-llama.cpp/blob/master/src/main/cpp/jllama.cpp#L831 but since I'm not super familiar with these bindings and llama.cpp I haven't figured out what's different in that condition.

Debugging this some more it seems like the token generated when it emits the angled bracket "faulty" `<|im_end>` is not the end of stream token, but the token for `<`.

### PR DESCRIPTION
**Pull request by hvisser**
Fixes #45

### CODE REVIEW

**Comment by kherud** [comment]
Thanks for the pull request! I changed it slightly to keep the default behavior, but allow to set `tokenize_special` via the `InferenceParameters` like:

```java
InferenceParameters inferParams = new InferenceParameters().setTokenizeSpecial(true);
// ...
model.generate(prompt, inferParams)
```

**Comment by hvisser** [comment]
Thanks, though I wonder why one would ever not want to tokenize these special tokens if the model has them. The whole point of adding these "special" tokens is to treat a sequence as a single token as I understand it. Moving this to the inference parameters puts the burden on the user of the library and since I was looking for the issue for a few hours, I suspect this isn't obvious for anyone encountering the same.

**Comment by kherud** [comment]
I agree, per default most users will want to tokenize these tokens. My reasoning was to stick to the default behavior of llama.cpp, where the parameter is false by default. I guess it's useful if you want to talk about those tokens as if they were text (or get answers containing them), without triggering their special functionality. I'll change the default to true in the Java binding, though.

**Comment by hvisser** [comment]
Changing the default is a good solution! Thanks again 😁

**Pull request merged**
